"""add_tags_translated_to_booklists

Revision ID: 018396567992
Revises: 704b2694ec0a
Create Date: 2026-03-09 00:14:14.355299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '018396567992'
down_revision: Union[str, Sequence[str], None] = '704b2694ec0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qidian_booklists', sa.Column('tags_translated', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qidian_booklists', 'tags_translated')
    # ### end Alembic commands ###
