"""add review_replies table

Revision ID: 01ee2da747a9
Revises: f1cbdacdae2b
Create Date: 2026-03-05 19:52:24.812424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01ee2da747a9'
down_revision: Union[str, Sequence[str], None] = 'f1cbdacdae2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['book_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_replies_review_id', 'review_replies', ['review_id'], unique=False)
    op.create_index('idx_review_replies_user_id', 'review_replies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_replies_user_id', table_name='review_replies')
    op.drop_index('idx_review_replies_review_id', table_name='review_replies')
    op.drop_table('review_replies')
    # ### end Alembic commands ###
