"""drop_creator_columns_from_booklists

Revision ID: 09a259c9c36b
Revises: 22074ca9d3cd
Create Date: 2026-03-07 06:06:42.364360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a259c9c36b'
down_revision: Union[str, Sequence[str], None] = '22074ca9d3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qidian_booklists', 'creator_name')
    op.drop_column('qidian_booklists', 'creator_name_translated')
    op.drop_column('qidian_booklists', 'creator_qidiantu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qidian_booklists', sa.Column('creator_qidiantu_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qidian_booklists', sa.Column('creator_name_translated', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('qidian_booklists', sa.Column('creator_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
