"""add qq_users book_comments and book sentiment fields

Revision ID: 18ac536e169d
Revises: 6fe08b4be362
Create Date: 2026-02-22 04:15:45.427198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18ac536e169d'
down_revision: Union[str, Sequence[str], None] = '6fe08b4be362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qq_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('nickname_translated', sa.String(length=255), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_author', sa.Integer(), nullable=True),
    sa.Column('center_author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qq_users_uid'), 'qq_users', ['uid'], unique=True)
    op.create_table('book_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.String(length=100), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('qq_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('title_translated', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_translated', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('agree_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('comment_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qq_user_id'], ['qq_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_comments_book_id', 'book_comments', ['book_id'], unique=False)
    op.create_index('idx_book_comments_book_sentiment', 'book_comments', ['book_id', 'sentiment'], unique=False)
    op.create_index('idx_book_comments_qq_user_id', 'book_comments', ['qq_user_id'], unique=False)
    op.create_index(op.f('ix_book_comments_comment_id'), 'book_comments', ['comment_id'], unique=True)
    op.add_column('books', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('last_comments_scraped_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'last_comments_scraped_at')
    op.drop_column('books', 'comment_count')
    op.drop_column('books', 'sentiment')
    op.drop_index(op.f('ix_book_comments_comment_id'), table_name='book_comments')
    op.drop_index('idx_book_comments_qq_user_id', table_name='book_comments')
    op.drop_index('idx_book_comments_book_sentiment', table_name='book_comments')
    op.drop_index('idx_book_comments_book_id', table_name='book_comments')
    op.drop_table('book_comments')
    op.drop_index(op.f('ix_qq_users_uid'), table_name='qq_users')
    op.drop_table('qq_users')
    # ### end Alembic commands ###
