"""add sorting indexes for bookmarks and reading progress

Revision ID: 19664477a7ff
Revises: 9762b1e92080
Create Date: 2026-03-06 21:39:11.292175

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '19664477a7ff'
down_revision: Union[str, Sequence[str], None] = '9762b1e92080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bookmarks_user_created', 'bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_books_update_time', 'books', ['update_time'], unique=False)
    op.create_index('idx_reading_progresses_user_last_read', 'reading_progresses', ['user_id', 'last_read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reading_progresses_user_last_read', table_name='reading_progresses')
    op.drop_index('idx_books_update_time', table_name='books')
    op.drop_index('idx_bookmarks_user_created', table_name='bookmarks')
    # ### end Alembic commands ###
