"""drop sentiment columns from book_stats

Revision ID: 196fb0e67e06
Revises: 09a259c9c36b
Create Date: 2026-03-07 22:53:06.257599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '196fb0e67e06'
down_revision: Union[str, Sequence[str], None] = '09a259c9c36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_stats', 'sentiment_positive')
    op.drop_column('book_stats', 'sentiment_neutral')
    op.drop_column('book_stats', 'sentiment_negative')
    op.add_column('books', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('sex_attr', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('qq_score', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('qq_score_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('qq_favorite_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('qq_fan_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('recommendation_qidian_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'recommendation_qidian_ids')
    op.drop_column('books', 'qq_fan_count')
    op.drop_column('books', 'qq_favorite_count')
    op.drop_column('books', 'qq_score_count')
    op.drop_column('books', 'qq_score')
    op.drop_column('books', 'sex_attr')
    op.drop_column('books', 'status')
    op.drop_column('books', 'word_count')
    op.add_column('book_stats', sa.Column('sentiment_negative', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('book_stats', sa.Column('sentiment_neutral', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('book_stats', sa.Column('sentiment_positive', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
