"""add_qidian_booklists

Revision ID: 22074ca9d3cd
Revises: bdec361f4dcc
Create Date: 2026-03-07 05:08:51.286137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22074ca9d3cd'
down_revision: Union[str, Sequence[str], None] = 'bdec361f4dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qidian_booklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qidiantu_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('title_translated', sa.String(length=500), nullable=True),
    sa.Column('creator_name', sa.String(length=255), nullable=True),
    sa.Column('creator_name_translated', sa.String(length=255), nullable=True),
    sa.Column('creator_qidiantu_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_translated', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_scraped_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qidiantu_id')
    )
    op.create_index('idx_qidian_booklists_qidiantu_id', 'qidian_booklists', ['qidiantu_id'], unique=False)
    op.create_table('qidian_booklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booklist_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('qidian_book_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('curator_comment', sa.Text(), nullable=True),
    sa.Column('curator_comment_translated', sa.Text(), nullable=True),
    sa.Column('heart_count', sa.Integer(), nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booklist_id'], ['qidian_booklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booklist_id', 'qidian_book_id', name='uq_booklist_qidian_book')
    )
    op.create_index('idx_qidian_booklist_items_book_id', 'qidian_booklist_items', ['book_id'], unique=False)
    op.create_index('idx_qidian_booklist_items_booklist_id', 'qidian_booklist_items', ['booklist_id'], unique=False)
    op.add_column('books', sa.Column('qidian_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('qidiantu_url', sa.String(length=512), nullable=True))
    op.create_unique_constraint('uq_books_qidian_id', 'books', ['qidian_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_books_qidian_id', 'books', type_='unique')
    op.drop_column('books', 'qidiantu_url')
    op.drop_column('books', 'qidian_id')
    op.drop_index('idx_qidian_booklist_items_booklist_id', table_name='qidian_booklist_items')
    op.drop_index('idx_qidian_booklist_items_book_id', table_name='qidian_booklist_items')
    op.drop_table('qidian_booklist_items')
    op.drop_index('idx_qidian_booklists_qidiantu_id', table_name='qidian_booklists')
    op.drop_table('qidian_booklists')
    # ### end Alembic commands ###
