"""drop_qq_catalog_entries_table

Revision ID: 32fa452ce4fd
Revises: a4845477115d
Create Date: 2026-03-04 22:29:15.653439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32fa452ce4fd'
down_revision: Union[str, Sequence[str], None] = 'a4845477115d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_qq_catalog_entries_book_id'), table_name='qq_catalog_entries')
    op.drop_index(op.f('idx_qq_catalog_entries_lookup'), table_name='qq_catalog_entries')
    op.drop_table('qq_catalog_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qq_catalog_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('finish_status', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('price_status', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('page', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('word_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('update_recency', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('order_by', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('qq_catalog_entries_book_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('qq_catalog_entries_pkey'))
    )
    op.create_index(op.f('idx_qq_catalog_entries_lookup'), 'qq_catalog_entries', ['category_id', 'subcategory_id', 'finish_status', 'price_status', 'word_count', 'update_recency', 'order_by', 'page', 'position'], unique=False)
    op.create_index(op.f('idx_qq_catalog_entries_book_id'), 'qq_catalog_entries', ['book_id'], unique=False)
    # ### end Alembic commands ###
