"""add translation tables

Revision ID: 3ffcef85a3c2
Revises: c196603ea682
Create Date: 2026-03-15 19:16:19.481563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ffcef85a3c2'
down_revision: Union[str, Sequence[str], None] = 'c196603ea682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_general_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('translated_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=20), server_default='term', nullable=False),
    sa.Column('gender', sa.String(length=1), server_default='N', nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'original_name', name='uq_user_general_entity')
    )
    op.create_index('idx_user_general_entities_user_id', 'user_general_entities', ['user_id'], unique=False)
    op.create_table('user_translation_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), server_default='free', nullable=False),
    sa.Column('byok_endpoint', sa.String(length=500), nullable=True),
    sa.Column('byok_model', sa.String(length=100), nullable=True),
    sa.Column('byok_key_enc', sa.Text(), nullable=True),
    sa.Column('byok_key_iv', sa.String(length=32), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_translation_settings_user_id', 'user_translation_settings', ['user_id'], unique=False)
    op.create_table('novel_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('translated_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=20), server_default='character', nullable=False),
    sa.Column('gender', sa.String(length=1), server_default='N', nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'original_name', name='uq_novel_entity')
    )
    op.create_index('idx_novel_entities_book_id', 'novel_entities', ['book_id'], unique=False)
    op.create_table('user_entity_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_entity_id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_entity_id'], ['novel_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'novel_entity_id', name='uq_user_entity_override')
    )
    op.create_index('idx_user_entity_overrides_entity_id', 'user_entity_overrides', ['novel_entity_id'], unique=False)
    op.create_index('idx_user_entity_overrides_user_id', 'user_entity_overrides', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_entity_overrides_user_id', table_name='user_entity_overrides')
    op.drop_index('idx_user_entity_overrides_entity_id', table_name='user_entity_overrides')
    op.drop_table('user_entity_overrides')
    op.drop_index('idx_novel_entities_book_id', table_name='novel_entities')
    op.drop_table('novel_entities')
    op.drop_index('idx_user_translation_settings_user_id', table_name='user_translation_settings')
    op.drop_table('user_translation_settings')
    op.drop_index('idx_user_general_entities_user_id', table_name='user_general_entities')
    op.drop_table('user_general_entities')
    # ### end Alembic commands ###
