"""drop sentiment column and index from book_comments

Revision ID: 48203f2482ca
Revises: 196fb0e67e06
Create Date: 2026-03-07 23:08:25.245170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48203f2482ca'
down_revision: Union[str, Sequence[str], None] = '196fb0e67e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_book_comments_book_sentiment'), table_name='book_comments')
    op.drop_column('book_comments', 'sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_comments', sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_book_comments_book_sentiment'), 'book_comments', ['book_id', 'sentiment'], unique=False)
    # ### end Alembic commands ###
