"""add book_stats table

Revision ID: 4868bd800e58
Revises: 32fa452ce4fd
Create Date: 2026-03-05 01:35:49.851268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4868bd800e58'
down_revision: Union[str, Sequence[str], None] = '32fa452ce4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_stats',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latest_chapter_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_positive', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_negative', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_neutral', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sentiment_positive', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sentiment_negative', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sentiment_neutral', sa.Integer(), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reader_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bookmark_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_stats')
    # ### end Alembic commands ###
