"""add_community_tags

Revision ID: 5b76dcf9ca7f
Revises: e71cc2cccba4
Create Date: 2026-03-10 21:14:04.938404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b76dcf9ca7f'
down_revision: Union[str, Sequence[str], None] = 'e71cc2cccba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('book_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'tag_id', 'user_id', name='uq_book_tag_user')
    )
    op.create_index('idx_book_tags_book_id', 'book_tags', ['book_id'], unique=False)
    op.create_index('idx_book_tags_tag_id', 'book_tags', ['tag_id'], unique=False)
    op.create_index('idx_book_tags_user_id', 'book_tags', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed initial tags
    seed_tags = [
        ("cultivation", "Cultivation"),
        ("system", "System"),
        ("reincarnation", "Reincarnation"),
        ("transmigration", "Transmigration"),
        ("romance", "Romance"),
        ("harem", "Harem"),
        ("face-slapping", "Face Slapping"),
        ("slow-burn", "Slow Burn"),
        ("op-mc", "OP MC"),
        ("weak-to-strong", "Weak to Strong"),
        ("kingdom-building", "Kingdom Building"),
        ("comedy", "Comedy"),
        ("tragedy", "Tragedy"),
        ("revenge", "Revenge"),
        ("academy", "Academy"),
        ("alchemy", "Alchemy"),
        ("beast-taming", "Beast Taming"),
        ("xuanhuan", "Xuanhuan"),
        ("xianxia", "Xianxia"),
        ("wuxia", "Wuxia"),
        ("urban", "Urban"),
        ("sci-fi", "Sci-Fi"),
        ("game-elements", "Game Elements"),
        ("clever-mc", "Clever MC"),
        ("antihero", "Antihero"),
        ("martial-arts", "Martial Arts"),
        ("time-loop", "Time Loop"),
        ("hidden-gem", "Hidden Gem"),
        ("villain-mc", "Villain MC"),
        ("mystery", "Mystery"),
    ]
    values = ", ".join(
        f"('{name}', '{display}', NOW())" for name, display in seed_tags
    )
    op.execute(
        f"INSERT INTO tags (name, display_name, created_at) VALUES {values} ON CONFLICT (name) DO NOTHING"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_book_tags_user_id', table_name='book_tags')
    op.drop_index('idx_book_tags_tag_id', table_name='book_tags')
    op.drop_index('idx_book_tags_book_id', table_name='book_tags')
    op.drop_table('book_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
