"""Add chapter url and untranslated indexes

Revision ID: 6215c7139f9b
Revises: 899ef2eacbc0
Create Date: 2026-02-23 05:26:32.772102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6215c7139f9b'
down_revision: Union[str, Sequence[str], None] = '899ef2eacbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chapters_untranslated', 'chapters', ['book_id', 'title_translated'], unique=False, postgresql_where=sa.text('title_translated IS NULL'))
    op.create_index('idx_chapters_url', 'chapters', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chapters_url', table_name='chapters')
    op.drop_index('idx_chapters_untranslated', table_name='chapters', postgresql_where=sa.text('title_translated IS NULL'))
    # ### end Alembic commands ###
