"""add_qidian_booklist_follows

Revision ID: 7c3e91af02d8
Revises: e9760d4190db
Create Date: 2026-03-10 21:34:18.492710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c3e91af02d8'
down_revision: Union[str, Sequence[str], None] = 'e9760d4190db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qidian_booklist_follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booklist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booklist_id'], ['qidian_booklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'booklist_id', name='uq_user_qidian_booklist_follow')
    )
    op.create_index('idx_qidian_booklist_follows_user_id', 'qidian_booklist_follows', ['user_id'], unique=False)
    op.create_index('idx_qidian_booklist_follows_booklist_id', 'qidian_booklist_follows', ['booklist_id'], unique=False)
    op.add_column('qidian_booklists', sa.Column('daosearch_follower_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qidian_booklists', 'daosearch_follower_count')
    op.drop_index('idx_qidian_booklist_follows_booklist_id', table_name='qidian_booklist_follows')
    op.drop_index('idx_qidian_booklist_follows_user_id', table_name='qidian_booklist_follows')
    op.drop_table('qidian_booklist_follows')
    # ### end Alembic commands ###
