"""add community ranking index

Revision ID: 82cc7866dda2
Revises: 19664477a7ff
Create Date: 2026-03-07 00:06:30.210707

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '82cc7866dda2'
down_revision: Union[str, Sequence[str], None] = '19664477a7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_rph_community_ranking', 'reading_progress_histories', ['recorded_at', 'book_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rph_community_ranking', table_name='reading_progress_histories')
    # ### end Alembic commands ###
