"""Remove sentiment and comment_count from books

Revision ID: 899ef2eacbc0
Revises: fa8a56e26f40
Create Date: 2026-02-23 02:21:46.316683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899ef2eacbc0'
down_revision: Union[str, Sequence[str], None] = 'fa8a56e26f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'sentiment')
    op.drop_column('books', 'comment_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
