"""add index on book_comments comment_created_at

Revision ID: 9762b1e92080
Revises: 01ee2da747a9
Create Date: 2026-03-06 05:40:55.394554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9762b1e92080'
down_revision: Union[str, Sequence[str], None] = '01ee2da747a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_book_comments_created_at', 'book_comments', [sa.literal_column('comment_created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_book_comments_created_at', table_name='book_comments')
    # ### end Alembic commands ###
