"""add word_count update_recency order_by to qq_catalog_entries

Revision ID: a4845477115d
Revises: b3c4d5e6f7a8
Create Date: 2026-03-01 12:50:52.938875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4845477115d'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qq_catalog_entries', sa.Column('word_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('qq_catalog_entries', sa.Column('update_recency', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('qq_catalog_entries', sa.Column('order_by', sa.Integer(), nullable=False, server_default='0'))
    op.drop_index(op.f('idx_qq_catalog_entries_lookup'), table_name='qq_catalog_entries')
    op.create_index('idx_qq_catalog_entries_lookup', 'qq_catalog_entries', ['category_id', 'subcategory_id', 'finish_status', 'price_status', 'word_count', 'update_recency', 'order_by', 'page', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qq_catalog_entries_lookup', table_name='qq_catalog_entries')
    op.create_index(op.f('idx_qq_catalog_entries_lookup'), 'qq_catalog_entries', ['category_id', 'subcategory_id', 'finish_status', 'price_status', 'page', 'position'], unique=False)
    op.drop_column('qq_catalog_entries', 'order_by')
    op.drop_column('qq_catalog_entries', 'update_recency')
    op.drop_column('qq_catalog_entries', 'word_count')
    # ### end Alembic commands ###
