"""remove entity_type columns

Revision ID: afb121a7d9f7
Revises: 3ffcef85a3c2
Create Date: 2026-03-15 19:35:54.186296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb121a7d9f7'
down_revision: Union[str, Sequence[str], None] = '3ffcef85a3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel_entities', 'entity_type')
    op.drop_column('user_general_entities', 'entity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_general_entities', sa.Column('entity_type', sa.VARCHAR(length=20), server_default=sa.text("'term'::character varying"), autoincrement=False, nullable=False))
    op.add_column('novel_entities', sa.Column('entity_type', sa.VARCHAR(length=20), server_default=sa.text("'character'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
