"""add reader tables and source_domain

Revision ID: ba59de34cdfd
Revises: bf5dc6d47393
Create Date: 2026-03-15 06:14:01.040450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba59de34cdfd'
down_revision: Union[str, Sequence[str], None] = 'bf5dc6d47393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('novel_url', sa.String(length=1000), nullable=False),
    sa.Column('last_checked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'domain', name='uq_book_source_domain')
    )
    op.create_index('idx_book_sources_book_id', 'book_sources', ['book_id'], unique=False)
    op.create_table('source_chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('last_fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'domain', 'sequence', name='uq_source_chapter')
    )
    op.create_index('idx_source_chapters_book_domain', 'source_chapters', ['book_id', 'domain'], unique=False)
    op.add_column('reading_progresses', sa.Column('source_domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_progresses', 'source_domain')
    op.drop_index('idx_source_chapters_book_domain', table_name='source_chapters')
    op.drop_table('source_chapters')
    op.drop_index('idx_book_sources_book_id', table_name='book_sources')
    op.drop_table('book_sources')
    # ### end Alembic commands ###
