"""add dao reader tables

Revision ID: bd5c7e515af7
Revises: afb121a7d9f7
Create Date: 2026-03-17 01:15:04.721173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd5c7e515af7'
down_revision: Union[str, Sequence[str], None] = 'afb121a7d9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translated_chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_seq', sa.Integer(), nullable=False),
    sa.Column('translated_title', sa.String(length=500), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('translated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', 'chapter_seq', name='uq_translated_chapter')
    )
    op.create_index('idx_translated_chapters_user_book', 'translated_chapters', ['user_id', 'book_id'], unique=False)
    op.create_table('user_novel_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('source_term', sa.String(length=255), nullable=False),
    sa.Column('translated_term', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=1), server_default='N', nullable=True),
    sa.Column('category', sa.String(length=50), server_default='character', nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', 'source_term', name='uq_user_novel_entity')
    )
    op.create_index('idx_user_novel_entities_user_book', 'user_novel_entities', ['user_id', 'book_id'], unique=False)
    op.create_index('idx_book_comments_book_agree', 'book_comments', ['book_id', sa.literal_column('agree_count DESC')], unique=False)
    op.create_index('idx_book_reviews_book_created', 'book_reviews', ['book_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_book_stats_chapter_count', 'book_stats', ['chapter_count'], unique=False)
    op.create_index('idx_book_stats_rating_count', 'book_stats', ['rating_count'], unique=False)
    op.create_index('idx_book_stats_reader_count', 'book_stats', ['reader_count'], unique=False)
    op.create_index('idx_book_stats_review_count', 'book_stats', ['review_count'], unique=False)
    op.create_index('idx_books_translated_created_at', 'books', ['created_at'], unique=False, postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.create_index('idx_books_translated_update_time', 'books', ['update_time'], unique=False, postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.create_index('idx_genres_id_blacklisted', 'genres', ['id', 'blacklisted'], unique=False)
    op.add_column('reading_progresses', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.add_column('reading_progresses', sa.Column('chapter_seq_override', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_progresses', 'chapter_seq_override')
    op.drop_column('reading_progresses', 'source_url')
    op.drop_index('idx_genres_id_blacklisted', table_name='genres')
    op.drop_index('idx_books_translated_update_time', table_name='books', postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.drop_index('idx_books_translated_created_at', table_name='books', postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.drop_index('idx_book_stats_review_count', table_name='book_stats')
    op.drop_index('idx_book_stats_reader_count', table_name='book_stats')
    op.drop_index('idx_book_stats_rating_count', table_name='book_stats')
    op.drop_index('idx_book_stats_chapter_count', table_name='book_stats')
    op.drop_index('idx_book_reviews_book_created', table_name='book_reviews')
    op.drop_index('idx_book_comments_book_agree', table_name='book_comments')
    op.drop_index('idx_user_novel_entities_user_book', table_name='user_novel_entities')
    op.drop_table('user_novel_entities')
    op.drop_index('idx_translated_chapters_user_book', table_name='translated_chapters')
    op.drop_table('translated_chapters')
    # ### end Alembic commands ###
