"""add_genre_blacklisted

Revision ID: bdec361f4dcc
Revises: fdd89174d227
Create Date: 2026-03-07 02:38:47.569970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdec361f4dcc'
down_revision: Union[str, Sequence[str], None] = 'fdd89174d227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('genres', sa.Column('blacklisted', sa.Boolean(), server_default='false', nullable=False))

    # Blacklist non-web-novel genres (textbooks, self-help, cooking, etc.)
    blacklisted_ids = (
        # Business / Self-Help / Finance
        9, 32, 11, 5, 76, 86, 33, 6, 171, 282, 283, 419, 236, 61, 366, 503,
        504, 505, 507, 539, 550, 552, 554, 582, 583, 584, 585, 587, 600, 614,
        642, 655, 657, 408, 271, 273, 501, 38, 476, 502, 738, 188, 548, 547,
        549, 551, 12, 186,
        # Academic / Education / Textbooks
        165, 51, 138, 176, 332, 139, 166, 403, 452, 453, 454, 455, 461, 417,
        328, 380, 535, 561, 621, 626, 627, 635, 636, 637, 640, 641, 638, 639,
        648, 769, 766, 767, 776, 777, 768, 784, 787, 792, 800, 801, 772, 770,
        527, 765, 760, 763, 764, 761, 440,
        # Non-Fiction / Reference / Biography
        73, 153, 149, 262, 87, 300, 316, 351, 189, 243, 269, 354, 395, 413,
        497, 530, 573, 574, 589, 619, 622, 624, 625, 645, 705, 785, 789, 803,
        77, 623, 183, 178, 394, 590, 598, 681,
        # Health / Medicine
        24, 34, 322, 313, 323, 331, 347, 350, 392, 416, 424, 474, 524, 545,
        568, 693, 696, 700, 706, 709, 710, 711, 712, 713, 714, 715, 708, 733,
        368, 692, 261, 35,
        # Psychology (academic)
        161, 172, 235, 266, 275, 276, 277, 278, 302, 303, 319, 370, 491, 516,
        521, 557, 562, 563, 567, 661, 662, 663, 664, 369,
        # Lifestyle / Parenting / Home
        151, 179, 390, 405, 427, 167, 448, 443, 152, 391, 393, 406, 407, 415,
        420, 428, 429, 430, 431, 432, 433, 441, 442, 447, 449, 450, 451, 462,
        471, 586, 699, 698, 702, 703, 704, 716, 720, 721, 726, 746, 790, 805,
        617, 616, 788, 372,
        # Technology / Engineering / Computers
        42, 356, 411, 43, 244, 246, 247, 248, 249, 252, 245, 414, 435, 436,
        437, 438, 439, 434, 456, 457, 458, 460, 487, 492, 493, 494, 496, 500,
        508, 509, 511, 517, 526, 528, 529, 553, 575, 611, 618, 679, 682, 684,
        686, 687, 688, 689, 690, 691, 741, 749, 773, 775, 783, 734, 580, 355,
        352, 357, 495, 659, 697, 750, 786, 781,
        # Politics / Law / Government
        92, 341, 137, 140, 93, 344, 396, 397, 399, 400, 486, 668, 342, 489,
        525, 541, 560, 601, 610, 615, 646, 647, 649, 650, 651, 482, 747, 748,
        759, 782, 791, 793, 807,
        # Sports (non-fiction)
        216, 555, 256, 217, 374, 386, 556, 565, 579, 591, 628, 630, 631, 632,
        701, 717, 718, 719, 629,
        # Children / Comics
        226, 1, 2, 296, 297, 613, 620, 227, 327, 381, 421, 737, 743, 665, 802,
        # Religion
        468, 469, 470, 564, 669, 670, 671, 672, 673, 674, 675, 676, 677,
        # Agriculture
        208, 209, 210, 211, 213, 214, 215, 751, 806,
        # Art / Music / Crafts
        335, 334, 301, 472, 510, 544, 570, 597, 607, 722, 723, 724, 730, 744,
        752, 757, 799, 446, 445, 444, 346, 595,
        # History / Culture (non-fiction reference)
        253, 279, 343, 546, 499, 506, 512, 515, 513, 225, 230, 274, 242, 348,
        150, 566, 581, 592, 593, 594, 602, 603, 604, 779, 780, 340, 173, 410,
        745, 656, 667, 728,
        # Philosophy (academic)
        10, 54, 184, 190, 287, 307, 314, 373, 384, 542, 571, 643, 644,
        # Self-improvement (non-fiction)
        44, 53, 59, 66, 170, 181, 187, 490, 308, 26, 13,
        # Military (non-fiction)
        304, 361, 364, 606, 633, 634, 284, 754, 762, 753,
        # Sociology / Anthropology
        174, 425, 409, 203, 202,
        # Literary criticism (non-fiction)
        223, 317, 241, 289, 286, 288, 154,
        # Reference / Journalism
        463, 401, 309, 318, 464, 465, 466, 467, 488, 612, 666, 725,
        # Miscellaneous non-fiction
        349, 459, 559, 569, 658, 678, 731, 732, 739, 740, 794, 795, 796, 797,
        804, 333, 479, 264, 353, 321, 330, 365, 680, 418, 519, 480, 263, 220,
        221, 736, 735, 798, 608, 609, 91, 78, 402, 543, 484, 514, 338, 339,
        345, 588, 727,
    )
    op.execute(
        sa.text(f"UPDATE genres SET blacklisted = true WHERE id IN ({','.join(str(i) for i in blacklisted_ids)})")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'blacklisted')
    # ### end Alembic commands ###
