"""add performance indexes for library and book detail queries

Revision ID: bf5dc6d47393
Revises: cf09d1e4791f
Create Date: 2026-03-11 00:42:52.609797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5dc6d47393'
down_revision: Union[str, Sequence[str], None] = 'cf09d1e4791f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_book_comments_book_agree', 'book_comments', ['book_id', sa.literal_column('agree_count DESC')], unique=False)
    op.create_index('idx_book_reviews_book_created', 'book_reviews', ['book_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_book_stats_chapter_count', 'book_stats', ['chapter_count'], unique=False)
    op.create_index('idx_book_stats_rating_count', 'book_stats', ['rating_count'], unique=False)
    op.create_index('idx_book_stats_reader_count', 'book_stats', ['reader_count'], unique=False)
    op.create_index('idx_book_stats_review_count', 'book_stats', ['review_count'], unique=False)
    op.create_index('idx_books_translated_created_at', 'books', ['created_at'], unique=False, postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.create_index('idx_books_translated_update_time', 'books', ['update_time'], unique=False, postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.create_index('idx_genres_id_blacklisted', 'genres', ['id', 'blacklisted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_genres_id_blacklisted', table_name='genres')
    op.drop_index('idx_books_translated_update_time', table_name='books', postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.drop_index('idx_books_translated_created_at', table_name='books', postgresql_where=sa.text('title_translated IS NOT NULL'))
    op.drop_index('idx_book_stats_review_count', table_name='book_stats')
    op.drop_index('idx_book_stats_reader_count', table_name='book_stats')
    op.drop_index('idx_book_stats_rating_count', table_name='book_stats')
    op.drop_index('idx_book_stats_chapter_count', table_name='book_stats')
    op.drop_index('idx_book_reviews_book_created', table_name='book_reviews')
    op.drop_index('idx_book_comments_book_agree', table_name='book_comments')
    # ### end Alembic commands ###
