"""add_booklist_tags

Revision ID: cf09d1e4791f
Revises: 5b76dcf9ca7f
Create Date: 2026-03-10 21:49:16.377034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf09d1e4791f'
down_revision: Union[str, Sequence[str], None] = '5b76dcf9ca7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booklist_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['book_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'tag_id', 'user_id', name='uq_booklist_tag_user')
    )
    op.create_index('idx_booklist_tags_list_id', 'booklist_tags', ['list_id'], unique=False)
    op.create_index('idx_booklist_tags_tag_id', 'booklist_tags', ['tag_id'], unique=False)
    op.create_index('idx_booklist_tags_user_id', 'booklist_tags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_booklist_tags_user_id', table_name='booklist_tags')
    op.drop_index('idx_booklist_tags_tag_id', table_name='booklist_tags')
    op.drop_index('idx_booklist_tags_list_id', table_name='booklist_tags')
    op.drop_table('booklist_tags')
    # ### end Alembic commands ###
