"""add_status_to_bookmarks

Revision ID: e71cc2cccba4
Revises: 7c3e91af02d8
Create Date: 2026-03-10 19:37:28.529330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71cc2cccba4'
down_revision: Union[str, Sequence[str], None] = '7c3e91af02d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index('idx_bookmarks_user_status', 'bookmarks', ['user_id', 'status'], unique=False)
    op.create_check_constraint(
        'ck_bookmark_status', 'bookmarks',
        "status IS NULL OR status IN ('reading', 'completed', 'dropped', 'plan_to_read')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_bookmark_status', 'bookmarks', type_='check')
    op.drop_index('idx_bookmarks_user_status', table_name='bookmarks')
    op.drop_column('bookmarks', 'status')
    # ### end Alembic commands ###
