"""add_public_booklist_support

Revision ID: eae8e629368a
Revises: 018396567992
Create Date: 2026-03-10 15:16:24.673265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae8e629368a'
down_revision: Union[str, Sequence[str], None] = '018396567992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_list_follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['book_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'list_id', name='uq_user_list_follow')
    )
    op.create_index('idx_book_list_follows_list_id', 'book_list_follows', ['list_id'], unique=False)
    op.create_index('idx_book_list_follows_user_id', 'book_list_follows', ['user_id'], unique=False)
    op.create_table('book_list_item_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['book_list_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item_like')
    )
    op.create_index('idx_book_list_item_likes_item_id', 'book_list_item_likes', ['item_id'], unique=False)
    op.create_index('idx_book_list_item_likes_user_id', 'book_list_item_likes', ['user_id'], unique=False)
    op.add_column('book_lists', sa.Column('follower_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('book_lists', sa.Column('item_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index('idx_book_lists_public', 'book_lists', ['is_public'], unique=False)
    # ### end Alembic commands ###

    # Backfill item_count from actual counts
    op.execute("""
        UPDATE book_lists
        SET item_count = sub.cnt
        FROM (
            SELECT list_id, COUNT(*) AS cnt
            FROM book_list_items
            GROUP BY list_id
        ) sub
        WHERE book_lists.id = sub.list_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_book_lists_public', table_name='book_lists')
    op.drop_column('book_lists', 'item_count')
    op.drop_column('book_lists', 'follower_count')
    op.drop_index('idx_book_list_item_likes_user_id', table_name='book_list_item_likes')
    op.drop_index('idx_book_list_item_likes_item_id', table_name='book_list_item_likes')
    op.drop_table('book_list_item_likes')
    op.drop_index('idx_book_list_follows_user_id', table_name='book_list_follows')
    op.drop_index('idx_book_list_follows_list_id', table_name='book_list_follows')
    op.drop_table('book_list_follows')
    # ### end Alembic commands ###
