"""drop novel_entities user_entity_overrides and category column

Revision ID: f11d6f700590
Revises: f27e35a10dd2
Create Date: 2026-03-18 18:42:38.276543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f11d6f700590'
down_revision: Union[str, Sequence[str], None] = 'f27e35a10dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_entity_overrides_user'), table_name='user_entity_overrides')
    op.drop_table('user_entity_overrides')
    op.drop_index(op.f('idx_novel_entities_book'), table_name='novel_entities')
    op.drop_table('novel_entities')
    op.drop_column('user_book_entities', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book_entities', sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'character'::character varying"), autoincrement=False, nullable=True))
    op.create_table('user_entity_overrides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('novel_entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['novel_entity_id'], ['novel_entities.id'], name=op.f('user_entity_overrides_novel_entity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_entity_overrides_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_entity_overrides_pkey')),
    sa.UniqueConstraint('user_id', 'novel_entity_id', name=op.f('uq_user_entity_override'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_entity_overrides_user'), 'user_entity_overrides', ['user_id'], unique=False)
    op.create_table('novel_entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('translated_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1), server_default=sa.text("'N'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('novel_entities_book_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('novel_entities_pkey')),
    sa.UniqueConstraint('book_id', 'original_name', name=op.f('uq_novel_entity'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_novel_entities_book'), 'novel_entities', ['book_id'], unique=False)
    # ### end Alembic commands ###
