"""add book_lists and book_list_items tables

Revision ID: f1cbdacdae2b
Revises: 4868bd800e58
Create Date: 2026-03-05 17:31:57.270677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1cbdacdae2b'
down_revision: Union[str, Sequence[str], None] = '4868bd800e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_lists_user_id', 'book_lists', ['user_id'], unique=False)
    op.create_table('book_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['book_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'book_id', name='uq_list_book')
    )
    op.create_index('idx_book_list_items_book_id', 'book_list_items', ['book_id'], unique=False)
    op.create_index('idx_book_list_items_list_id', 'book_list_items', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_book_list_items_list_id', table_name='book_list_items')
    op.drop_index('idx_book_list_items_book_id', table_name='book_list_items')
    op.drop_table('book_list_items')
    op.drop_index('idx_book_lists_user_id', table_name='book_lists')
    op.drop_table('book_lists')
    # ### end Alembic commands ###
