"""rename user_novel_entities to user_book_entities

Revision ID: f27e35a10dd2
Revises: a840a59a3eef
Create Date: 2026-03-18 06:43:11.989391

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f27e35a10dd2'
down_revision: Union[str, Sequence[str], None] = 'a840a59a3eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Rename user_novel_entities table and its constraints/indexes."""
    # Rename table
    op.rename_table('user_novel_entities', 'user_book_entities')

    # Rename unique constraint
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT uq_user_novel_entity TO uq_user_book_entity')

    # Rename index
    op.execute('ALTER INDEX idx_user_novel_entities_user_book RENAME TO idx_user_book_entities_user_book')

    # Rename sequence (auto-generated by SERIAL column)
    op.execute('ALTER SEQUENCE user_novel_entities_id_seq RENAME TO user_book_entities_id_seq')

    # Rename foreign key constraints
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT user_novel_entities_user_id_fkey TO user_book_entities_user_id_fkey')
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT user_novel_entities_book_id_fkey TO user_book_entities_book_id_fkey')

    # Rename primary key constraint
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT user_novel_entities_pkey TO user_book_entities_pkey')


def downgrade() -> None:
    """Revert rename back to user_novel_entities."""
    # Rename primary key constraint
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT user_book_entities_pkey TO user_novel_entities_pkey')

    # Rename foreign key constraints
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT user_book_entities_book_id_fkey TO user_novel_entities_book_id_fkey')
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT user_book_entities_user_id_fkey TO user_novel_entities_user_id_fkey')

    # Rename sequence
    op.execute('ALTER SEQUENCE user_book_entities_id_seq RENAME TO user_novel_entities_id_seq')

    # Rename index
    op.execute('ALTER INDEX idx_user_book_entities_user_book RENAME TO idx_user_novel_entities_user_book')

    # Rename unique constraint
    op.execute('ALTER TABLE user_book_entities RENAME CONSTRAINT uq_user_book_entity TO uq_user_novel_entity')

    # Rename table
    op.rename_table('user_book_entities', 'user_novel_entities')
