"""remove comment_id from book_comments

Revision ID: fa8a56e26f40
Revises: abacb7ab4836
Create Date: 2026-02-22 04:48:31.707795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8a56e26f40'
down_revision: Union[str, Sequence[str], None] = 'abacb7ab4836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_comments_comment_id'), table_name='book_comments')
    op.drop_column('book_comments', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_comments', sa.Column('comment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_book_comments_comment_id'), 'book_comments', ['comment_id'], unique=True)
    # ### end Alembic commands ###
