"""add_trgm_indexes

Revision ID: fdd89174d227
Revises: 82cc7866dda2
Create Date: 2026-03-07 01:51:52.285100

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'fdd89174d227'
down_revision: Union[str, Sequence[str], None] = '82cc7866dda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_books_author_translated_trgm', 'books', ['author_translated'], unique=False, postgresql_using='gin', postgresql_ops={'author_translated': 'gin_trgm_ops'})
    op.create_index('idx_books_author_trgm', 'books', ['author'], unique=False, postgresql_using='gin', postgresql_ops={'author': 'gin_trgm_ops'})
    op.create_index('idx_books_title_translated_trgm', 'books', ['title_translated'], unique=False, postgresql_using='gin', postgresql_ops={'title_translated': 'gin_trgm_ops'})
    op.create_index('idx_books_title_trgm', 'books', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_books_title_trgm', table_name='books', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_books_title_translated_trgm', table_name='books', postgresql_using='gin', postgresql_ops={'title_translated': 'gin_trgm_ops'})
    op.drop_index('idx_books_author_trgm', table_name='books', postgresql_using='gin', postgresql_ops={'author': 'gin_trgm_ops'})
    op.drop_index('idx_books_author_translated_trgm', table_name='books', postgresql_using='gin', postgresql_ops={'author_translated': 'gin_trgm_ops'})
    # ### end Alembic commands ###
