// Primary genres from the API — used as slash command choices (max 25)
export const GENRE_CHOICES: { name: string; value: string }[] = [
  { name: "Ancient Romance", value: "14" },
  { name: "Esports", value: "234" },
  { name: "Fantasy", value: "119" },
  { name: "Fantasy Romance", value: "28" },
  { name: "Game", value: "99" },
  { name: "General Fiction", value: "18" },
  { name: "History", value: "20" },
  { name: "Light Novel", value: "16" },
  { name: "Literature", value: "143" },
  { name: "Martial Arts", value: "110" },
  { name: "Military", value: "194" },
  { name: "Modern Romance", value: "25" },
  { name: "Multiverse", value: "45" },
  { name: "Mystery", value: "68" },
  { name: "Realistic Fiction", value: "359" },
  { name: "Sci-Fi", value: "22" },
  { name: "Science Fiction", value: "37" },
  { name: "Short Fiction", value: "191" },
  { name: "Slice of Life", value: "218" },
  { name: "Suspense", value: "133" },
  { name: "Urban", value: "40" },
  { name: "Xianxia", value: "7" },
  { name: "Xianxia Fantasy", value: "65" },
  { name: "Xuanhuan", value: "63" },
  { name: "Young Adult", value: "79" },
];
